### PR TITLE
updating configuration files and allowing trajectory execution

### PR DESCRIPTION
**Pull request by sfoix**

### CODE REVIEW

**Comment by 130s** [comment]
LGTM with a quick glimpse, but I have no hand to test this.

**Comment by sfoix** [comment]
You should be able to test it if you checkout these two repositories:

https://devel.iri.upc.edu/pub/labrobotica/ros/iri-ros-pkg_hydro/metapackages/iri_wam/iri_wam_description
https://devel.iri.upc.edu/pub/labrobotica/ros/iri-ros-pkg_hydro/metapackages/iri_wam/iri_wam_gazebo

and launch:

roslaunch iri_wam_gazebo iri_wam.launch

and then:

roslaunch iri_wam_moveit_config moveit_planning_execution.launch

**Comment by sfoix** [comment]
Hi,

Any news?

Regards

**Comment by davetcoleman** [comment]
lgtm +1

**Comment by v4hn** [comment]
@davetcoleman you just merged this request (thanks for the squash-merge) and it breaks the build.
> running build
> running build_py
> error: package directory 'scripts/simple_example' does not exist

I'll have a look, but it would be great if you could setup `moveit_ci` testing for this repo too.

**Comment by v4hn** [comment]
I just pushed f85906708ca67d823ac0201548527f3116639a99 .
That resolved the error.

**Comment by davetcoleman** [comment]
I've added moveit_ci
https://github.com/ros-planning/moveit_robots/pull/48

**Pull request merged**
