### PR TITLE
add dummy joint trajectory server and update demo_sim.launch

### PR DESCRIPTION
**Pull request by k-okada**
When I found demo_sim.launch, I thought this is the launch file for those who do not have real baxter nor baxter gazebo simulation, but it seems not.
One easiest solution is to set `allow_trajectory_execution` to false (http://moveit.ros.org/wiki/MoveGroup_Node) to disable `Execute` button. but I do no like to see the baxter in the rviz is still in initial position.
If MoveIt! provides something like loopback trajectory execution, that just to update robot posture from trajectory execution, I'd like to use that.

This PR contains joint_trajectory_controller that takes FollowJointTrajectory and publishes joint states, so if you launch demo_sim.launch, you can use MoveIt without realrobot/gazebo.

### CODE REVIEW

**Comment by 130s** [comment]
+1. Is there any blocking factor? @rethink-imcmahon

**Comment by mikeferguson** [comment]
@130s this PR says it can't be merged due to conflicts -- so that is certainly blocking.

**Comment by 130s** [comment]
Oh right @mikeferguson. Would you rebase @k-okada if you haven't done yet?

**Comment by k-okada** [comment]
hum this PR was ok for merge a month ago, fixed.

**Comment by rethink-imcmahon** [comment]
@130s All clear here! :shipit:

**Comment by 130s** [comment]
Okay, can any maintainer take a look? I only see [this guy in package.xml](https://github.com/k-okada/moveit_robots/blob/add_dummy_joint_trajectory_controller/baxter/baxter_moveit_config/package.xml#L9):
```
 <maintainer email="assistant@moveit.ros.org">MoveIt Setup Assistant</maintainer>
```

**Comment by mikeferguson** [comment]
Looks like we have the proper signoffs -- merging

**Pull request merged**
