### PR TITLE
fix ikfast.h location

### LINKED ISSUE #37: apt error "trying to overwrite '/opt/ros/indigo/include/ikfast.h', which is also in package ros-indigo-baxter-ikfast-right"
Installing `baxter_moveit_config` deb fails since its dependency `baxter-ikfast-{left, right}-arm-plugin` both tries to install `/opt/ros/indigo/include/ikfast.h` and apt seems to not be able to handle it.

```
$ sudo apt-get install ros-indigo-baxter-ikfast-right-arm-plugin 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  ros-indigo-baxter-ikfast-right-arm-plugin
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/299 kB of archives.
After this operation, 1,359 kB of additional disk space will be used.
(Reading database ... 550155 files and directories currently installed.)
Preparing to unpack .../ros-indigo-baxter-ikfast-right-arm-plugin_1.0.2-0trusty-20150922-1144-+0000_amd64.deb ...
Unpacking ros-indigo-baxter-ikfast-right-arm-plugin (1.0.2-0trusty-20150922-1144-+0000) ...
Setting up ros-indigo-baxter-ikfast-right-arm-plugin (1.0.2-0trusty-20150922-1144-+0000) ...
$ sudo apt-get install ros-indigo-baxter-ikfast-left-arm-plugin 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  ros-indigo-baxter-ikfast-left-arm-plugin
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/299 kB of archives.
After this operation, 1,359 kB of additional disk space will be used.
Selecting previously unselected package ros-indigo-baxter-ikfast-left-arm-plugin.
(Reading database ... 550166 files and directories currently installed.)
Preparing to unpack .../ros-indigo-baxter-ikfast-left-arm-plugin_1.0.2-0trusty-20150922-1144-+0000_amd64.deb ...
Unpacking ros-indigo-baxter-ikfast-left-arm-plugin (1.0.2-0trusty-20150922-1144-+0000) ...
dpkg: error processing archive /var/cache/apt/archives/ros-indigo-baxter-ikfast-left-arm-plugin_1.0.2-0trusty-20150922-1144-+0000_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/indigo/include/ikfast.h', which is also in package ros-indigo-baxter-ikfast-right-arm-plugin 1.0.2-0trusty-20150922-1144-+0000
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/ros-indigo-baxter-ikfast-left-arm-plugin_1.0.2-0trusty-20150922-1144-+0000_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
With `catkin_make install`, this isn't an issue since I assume either package just overwrites the .h file that's installed by the other?

I don't know what's the best solution for this. Apparently we can extract the shared portion as a common package but that may sound a bit overkill.

### PR DESCRIPTION
**Pull request by k-okada**
this will fixes #37

- use include/baxter_ikfast_{left/right}_arm_plugin/ikfast.h
- mv ikfast.h from include/ to include/baxter_ikfast_{left/right}_arm_plugin/include

### CODE REVIEW

**Comment by rethink-imcmahon** [comment]
+1 this seems like a good solution to #37 to me. Thanks @k-okada!

**Comment by 130s** [comment]
+1 

Confirmed locally.
```
$ catkin config --install
$ catkin build moveit_robots
$ source ./install/setup.bash 
$ find ./install/ -iname ikfast.h
./install/include/baxter_ikfast_left_arm_plugin/ikfast.h
./install/include/baxter_ikfast_right_arm_plugin/ikfast.h
```

**Comment by 130s** [comment]
DEB request is flying https://github.com/ros/rosdistro/pull/9748 for indigo.

**Comment by rethink-imcmahon** [comment]
Thanks for blooming this, @130s

**Pull request merged**
