### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by davetcoleman**
I'm opening this pull request to continue to test why the CI is broken, per https://github.com/ros-planning/moveit_robots/pull/59#issuecomment-289512786

Also switching back to the correct moveit_ci branch.

### CODE REVIEW

**Comment by davetcoleman** [comment]
I've tracked down the issue but do not have a fix: https://github.com/catkin/catkin_tools/issues/453

**Comment by davetcoleman** [comment]
@v4hn

**Comment by davetcoleman** [comment]
I've fixed the CI, this is ready to be merged

**Comment by v4hn** [comment]
Sorry this took me so long...

**Pull request merged**
