### PR TITLE
Install scripts/dummy_joint_trajectory_controller in baxter_moveit_config

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by v4hn** [comment]
Could you please install the only python script in there via [catkin_install_python](http://docs.ros.org/indigo/api/catkin/html/howto/format1/installing_python.html)?

The dummy_joint_trajectory_controller seems to be quite useful and as far as I can see, it's not restricted to the baxter robot, is it?
I was missing such a node just yesterday!
Would it be a good idea to move this out of the `baxter_moveit_config` package and create a new package "fake_joint_trajectory_controller" in `moveit_ros` for it instead?

**Comment by wkentaro** [comment]
Updated.

> The dummy_joint_trajectory_controller seems to be quite useful and as far as I can see, it's not restricted to the baxter robot, is it?
I was missing such a node just yesterday!
Would it be a good idea to move this out of the baxter_moveit_config package and create a new package "fake_joint_trajectory_controller" in moveit_ros for it instead?

I think that is a good idea.

**Comment by v4hn** [comment]
@wkentaro: Is the node functional with non-baxter robots "as is"?
Could you write a pull_request that adds the new package to moveit_ros?
Then, we could remove this script from in here entirely and redirect the launch files to the new package, instead of installing it in here.

**Comment by wkentaro** [comment]
Sent https://github.com/ros-planning/moveit_ros/pulls

**Comment by v4hn** [comment]
Hey @wkentaro ,

@rhaschke spent quite a bit of time on dummy execution controllers in https://github.com/ros-planning/moveit_plugins/pull/23 and now we have interpolating fake controllers as default in MoveIt! (across all three branches).
Could you have a look at them and check whether these are good enough for your use-case?
If this is the case, I would propose to *remove* the `dummy_joint_trajectory_controller` and the corresponding launch files instead of adding the install rule.

**Comment by wkentaro** [comment]
I'm not sure how to use the fake controller for Baxter.

**Comment by v4hn** [comment]
On Mon, Aug 22, 2016 at 10:22:45PM -0700, Kentaro Wada wrote:

> I'm not sure how to use the fake controller for Baxter.

@rhaschke could you please have a quick look and comment?

**Comment by rhaschke** [comment]
@wkentaro: I just fixed the formatting of the [README](https://github.com/ros-planning/moveit/tree/indigo-devel/moveit_plugins/moveit_fake_controller_manager). Please have a look, If you need further assistance, please don't hesitate to contact me. In that case, the documentation isn't good enough yet ;-)

**Comment by wkentaro** [comment]
@rhaschke Yeah, the format was broken, so I looked the tutorial.rst. However, I had error because of not found type of `type: interpolate | via points | last point` at my last trial. Are there any examples?

**Comment by davetcoleman** [comment]
Can this PR be closed now that MoveIt! includes a proper dummy joint controller? https://github.com/ros-planning/moveit_plugins/pull/23

**Pull request closed without merging**
