### PR TITLE
set RRT as default planner

### PR DESCRIPTION
**Pull request by k-okada**
set default planning config, which is supported on moveit 0.7
https://github.com/ros-planning/moveit_ros/pull/625

### CODE REVIEW

**Comment by rethink-imcmahon** [comment]
This is very interesting! If no planner was specified before, what would MoveIt default to? Was it RRTConnect? I would like to keep the functionality the same, if possible.

**Comment by k-okada** [comment]
Currently, they use LBKPIECE as a default planner and it tend to generate
redundant path or sometimes it failed to find solution, whereas rrt gives
better solution.
I haven't choose RRT just because I'm familiar with that, did not compared
with other algorithms.

--
◉ Kei Okada

**Comment by rethink-imcmahon** [comment]
That rational sounds good to me. I happen to use RRTConnect in a lot of my testing for exactly that reason.

**Comment by rethink-imcmahon** [comment]
Thanks for the contribution @k-okada!

**Pull request merged**
