### PR TITLE
[baxter_moveit_config] add gripper option for robot_description

### PR DESCRIPTION
**Pull request by knorth55**
in case of no gripper, robot_description should not contain gripper description

Requires https://github.com/RethinkRobotics/baxter_common/pull/79

### CODE REVIEW

**Comment by davetcoleman** [comment]
Travis is failing because no baxter_description in Kinetic, see https://github.com/RethinkRobotics/baxter_common/issues/80

**Comment by knorth55** [comment]
what should i do for this? temporary close this PR?

**Comment by davetcoleman** [comment]
You/we could set a `BEFORE_SCRIPT` in the `.travis.yml` file as documented [here](https://github.com/ros-planning/moveit_ci/) to also `git clone` the baxter_common repo.

**Comment by knorth55** [comment]
I add `BEFORE_SCRIPT` in order to `git clone` `baxter_common` repo.

**Comment by davetcoleman** [comment]
Nice!

**Pull request merged**
