### PR TITLE
[baxter_moveit_config] add launch_sensor option to choose whether start sensor or not

### PR DESCRIPTION
**Pull request by aginika**
I added launch_sensor args in launch files.
Default is true, but when you won't launch the sensor, you should set false.
This time, I added `if` condition to `static_transform_publisher` too.

### CODE REVIEW

**Comment by rethink-imcmahon** [comment]
Thanks for the pull request, Yuto & Kentaro. What benefit does this preset over leaving `kinect:=false` and `xtion:= false`?

**Comment by aginika** [comment]
This option will work only when `kinect:=true` or `xtion:=true`.

We include this moveit_config from other launch and we often launch sensors in other launch too, so this will crash sensors launch nodes.
With this PR, we can switch whether to launch sensor or not and prevent crashing.

**Comment by rethink-imcmahon** [comment]
Interesting! I hadn't anticipated that use case. Is there any reason you are setting `kinect` and `xtion` to be true in the first place? I don't forsee any issue with this PR, but I want to be sure the new param is needed.

**Comment by aginika** [comment]
> I hadn't anticipated that use case. Is there any reason you are setting kinect and xtion to be true in the first place?

means below part?
```
<arg name="launch_sensor" default="true"/>
```

I couldn't decide what should be as default.
I think most of the user will use this launch as stand-alone, so I make it true as default.(A user just need to make kinect or xtion true, if they want to use sensor)

**Comment by rethink-imcmahon** [comment]
Right, I don't see any harm in this change, but I am curious why the `launch_sensor` parameter is needed at all: 
If you are using the kinect, set `kinect:=true` (`xtion` defaults to `false`)
If you are using the xtion, set `xtion:=true` (`kinect` defaults to `false`)
If you don't want to launch a sensor, leave default arguments (`kinect` and `xtion` both default to `false`)

With that in mind, does `launch_sensor` give you anything that is not already captured by these arguments?

**Comment by aginika** [comment]
The `launch_sensor` param only stop launching the sensor drivers.
I want to to use this when
* I want to take it into account point cloud output to moveit (need to load rosparams)
* but I already launch the sensor drivers

Below part will not be disabled when `launch_sensor` is true.
```
 <!-- octomap parameters for moveit -->
         <group ns="move_group" >
             <param name="octomap_frame" type="string" value="camera_link" />
             <param name="octomap_resolution" type="double" value="0.02" />
             <rosparam command="load" file="$(find baxter_moveit_config)/config/xtion_sensor.yaml" />
         </group>
```

**Comment by 130s** [comment]
@rethink-imcmahon Does the last comment is satisfactory before this gets merged?

**Comment by rethink-imcmahon** [comment]
@aginika & @130s, sorry I let this review slide for so long. @aginika, is there any circumstance where you would set `kinect:=true launch_sensor:=false`? That senario seems to be the only reason to include the extra arg (otherwise you'd get the desired behavior with `kinect:=false`)

**Comment by aginika** [comment]
Sorry for late replay.

I think I tought (at that time) I would like to use it with another launch which will launch kinect.
But , as you said, I think in that case, I just should change the another launch.
Thanks for your advise!

**Comment by rethink-imcmahon** [comment]
@aginika Oh, the second Kinect use case actually makes quite a bit of sense. I hadn't thought of that. It is likely not very common, so I think we are fine without merging this pull, but I appreciate your explanantion.

As you say, for your situtation, just changing the launchfile should work fine. I was  trying to hedge against extra complexity in the (already complex) launch files. Your pull requests are always appreciated, so I hope to see more in the future :) Thanks!

**Pull request closed without merging**
